betagouv/anssi-portail

.github/workflows/deploiement.yml
.github/workflows/integration-continue.yml
Dockerfile
README.md
_config.yml
index.markdown

🧱 Cette PR pose les fondations du produit :
- un site statique généré via Jekyll 
- la génération se fait sur chaque PR, pour valider que le code est correct
- le déploiement vers le PaaS se fait via la CI/CD

Initialise Jekyll et l'infrastructure de déploiement

---

_includes/head.html
_layouts/service.html
assets/service.scss
assets/site.scss
scripts/service.js

Cette PR rajoute un menu de navigation complet et fonctionnel.
En mode inactif 👇 
Il prend tout l'écran quand il est ouvert, et navigue vers la section cliquée, qui devient _active_ 👇

Implémente le menu de navigation

---

_layouts/service.html
assets/responsive.scss
assets/service.scss

Adapte le contenu sur les tablettes de la page service

---

_layouts/service.html
_services/mon-service-securise.md
assets/responsive.scss
assets/service.scss
assets/site.scss
scripts/service.js

Cette PR adapte la page service à l'affichage bureau 👇

La page Service en version bureau

---

_layouts/service.html
assets/responsive.scss
assets/service.scss

Adapte la page service pour les écrans extra larges

---

Dockerfile
README.md
_config.yml
_includes/footer.html
_layouts/catalogue.html
_layouts/defaut.html
_layouts/service.html
_ressources/livret-cyber-enjeux.md
_services/mon-aide-cyber.md
_services/mon-service-securise.md
assets/styles/catalogue.scss
assets/styles/service.scss
assets/styles/site.scss
catalogue.html
dev.sh
lib-catalogue/.gitignore
lib-catalogue/README.md
lib-catalogue/index.html
lib-catalogue/package-lock.json
lib-catalogue/package.json
lib-catalogue/src/Catalogue.svelte
lib-catalogue/src/Catalogue.types.ts
lib-catalogue/src/main.ts
lib-catalogue/src/vite-env.d.ts
lib-catalogue/svelte.config.js
lib-catalogue/tsconfig.json
lib-catalogue/tsconfig.node.json
lib-catalogue/vite.config.ts

Cette PR pose les fondations du catalogue :
- un composant Svelte …
- … buildé juste avant le Jekyll …
- … et servi par celui-ci

Démarrage de la page Catalogue

---

_ressources/livret-cyber-enjeux.md
_services/mon-aide-cyber.md
_services/mon-service-securise.md
assets/styles/catalogue.scss
catalogue.html
lib-catalogue/src/Catalogue.svelte
lib-catalogue/src/Catalogue.types.ts
lib-catalogue/src/FiltreAccessibilite.svelte
lib-catalogue/src/FiltreBesoin.svelte
lib-catalogue/src/stores/catalogueFiltre.store.ts
lib-catalogue/src/stores/nombreResultats.store.ts
lib-catalogue/src/stores/rechercheParDroitAcces.store.ts
lib-catalogue/test/stores/catalogueFiltre.store.spec.ts
lib-catalogue/test/stores/nombreResultats.store.spec.ts
lib-catalogue/test/stores/objetsExemples.ts

Filtre le catalogue sur les droits d’accès

---

_layouts/service.html
_ressources/demain-specialiste-cyber.md
_services/mon-aide-cyber.md
_services/mon-service-securise.md
assets/styles/service.scss
assets/styles/site.scss
lib-catalogue/src/Catalogue.svelte

Quelques corrections visuelles et référence désormais directement les ressources associées grâce à leur id

Apporte des retouches à la page service

---

_ressources/demain-specialiste-cyber.md
_ressources/livret-cyber-enjeux.md
assets/styles/catalogue.scss
catalogue.html
lib-catalogue/src/Catalogue.svelte
lib-catalogue/src/Catalogue.types.ts
lib-catalogue/src/FiltreTypologieEtFormat.svelte
lib-catalogue/src/stores/catalogueFiltre.store.ts
lib-catalogue/src/stores/nombreResultats.store.ts
lib-catalogue/src/stores/rechercheParBesoin.store.ts
lib-catalogue/src/stores/rechercheParDroitAcces.store.ts
lib-catalogue/src/stores/rechercheParFormat.store.ts
lib-catalogue/src/stores/rechercheParTypologie.store.ts
lib-catalogue/test/stores/catalogueFiltre.store.spec.ts
lib-catalogue/test/stores/nombreResultats.store.spec.ts
lib-catalogue/test/stores/objetsExemples.ts

Filtre sur les typologies et les formats

---

_ressources/kit-cyber.md
_ressources/livret-cyber-enjeux.md
_services/ads.md
_services/mon-aide-cyber.md
lib-catalogue/src/Catalogue.svelte
lib-catalogue/src/Catalogue.types.ts
lib-catalogue/src/FiltreSource.svelte
lib-catalogue/src/stores/catalogueFiltre.store.ts
lib-catalogue/src/stores/nombreResultats.store.ts
lib-catalogue/src/stores/rechercheParSource.store.ts
lib-catalogue/test/stores/catalogueFiltre.store.spec.ts
lib-catalogue/test/stores/nombreResultats.store.spec.ts
lib-catalogue/test/stores/objetsExemples.ts
lib-catalogue/test/stores/rechercheParSource.store.spec.ts

Filtre le catalogue sur la source

---

_ressources/demain-specialiste-cyber.md
_ressources/kit-cyber.md
_ressources/livret-cyber-enjeux.md
_services/ads.md
_services/mon-aide-cyber.md
_services/mon-service-securise.md
catalogue.html
lib-catalogue/src/Catalogue.svelte
lib-catalogue/src/Catalogue.types.ts
lib-catalogue/src/FiltreTheme.svelte
lib-catalogue/src/stores/catalogueFiltre.store.ts
lib-catalogue/src/stores/nombreResultats.store.ts
lib-catalogue/src/stores/rechercheParTheme.store.ts
lib-catalogue/test/stores/catalogueFiltre.store.spec.ts
lib-catalogue/test/stores/nombreResultats.store.spec.ts
lib-catalogue/test/stores/objetsExemples.ts

Filtre le catalogue sur le thème Cyber

---

assets/styles/catalogue.scss
assets/styles/service.scss
assets/styles/site.scss

... suite à la recette de l’UI

Corrige des aspects visuels 

---

_includes/footer.html
_includes/header.html
_layouts/service.html
assets/styles/catalogue.scss
assets/styles/responsive.scss
assets/styles/service.scss
assets/styles/site.scss
catalogue.html
lib-catalogue/src/Catalogue.svelte

Afin de respecter l’affichage DSFR, on limite la largeur du contenu à 1200px. La gouttière s’agrandit lorsque le contenu a atteint sa largeur maximale.

Limite la largeur du contenu des pages

---

_includes/footer.html
_includes/head.html
_includes/header.html
assets/images/icone-croix.svg
assets/styles/site.scss
index.html
lib-svelte/src/test-maturite/PubliciteMesServicesCyber.svelte
lib-svelte/src/test-maturite/ResultatsTestMaturite.svelte
parcours-approfondir.html
parcours-debuter.html
scripts/navigation-mobile.js

Cette PR ajoute un menu correct sur mobile👇

Ajout du menu mobile

---

.github/workflows/deploiement.yml

Changement classique du `yml` de déploiement.

Autorise le déploiement en PROD

---

.github/workflows/deploiement.yml

On veut seulement déployer la DÉMO **après** la PROD.

Ajustement du déploiement vers la PROD

---

_includes/header.html
assets/styles/site.scss

Affiche le logo ANSSI et le titre dans l’entête

---

_includes/header.html
assets/styles/site.scss
index.html
lib-svelte/src/test-maturite/PubliciteMesServicesCyber.svelte
parcours-approfondir.html
parcours-debuter.html

Cette PR ajoute le menu de navigation desktop 👇 
… et fait quelques ajustements.

Navigation desktop

---

_includes/carte-item.html
assets/styles/service.scss
assets/styles/test-maturite.scss
index.html
lib-svelte/src/test-maturite/SelectRegion.svelte
lib-svelte/src/test-maturite/SelectSecteurActivite.svelte
lib-svelte/src/test-maturite/TestMaturite.svelte

Suite de #55 qui ne contenait pas tous les commits.

Navigation desktop 

---

assets/styles/test-maturite.scss

Cette PR corrige le rognage de la première tuile de résultat 👇 
… et ajoute une animation 👇 
https://github.com/user-attachments/assets/ad3f3264-f625-491c-ab1a-6dcfa8c953e0

Correction sur résultat du test

---

assets/styles/accueil.scss
assets/styles/boutons.scss
assets/styles/catalogue.scss
assets/styles/service.scss
assets/styles/site.scss
assets/styles/test-maturite.scss
lib-svelte/src/test-maturite/TestMaturite.svelte

Cette PR ajoute les comportements de `hover` et `active` sur les liens.

Gestion du survol et du clic sur les liens

---

_services/pack-parcours-secu.md
lib-svelte/src/Hero.svelte

Ajoute un droit d'accès à la fiche du Parcours Sécu sinon, en l'état, ça casse les filtres du catalogue.

Droits accès pack parcours

---

_ressources/cyber-dico.md
_ressources/panorama.md
_ressources/risques-cyber.md
_services/ads.md
_services/conseil-technique.md

J'avais fait des petites erreurs hier en fin d'apres midi sur des sources ou autre - c'est corrigé !

Correction coquille delta grist

---

.github/workflows/integration-continue.yml
.gitignore
_config.yml
_includes/head.html
package-lock.json
package.json
scripts/parcours.js
scripts/scroll.js
test/scroll.test.js
vitest.config.js

Cette PR synchronise la section visible et l'élément actif du menu 👇 
> [!WARNING]
> On sait que cette PR n'adresse pas complètement le cas du mobile. Le menu actif change bien… mais il n'est pas forcément visible à l'écran car il est « hors écran » sur la droite ou la gauche. On a tenté de le `scrollIntoView` mais sans succès : ça donne des conflits de scroll vertical & horizontal. Pour l'instant on reste comme ça.

Ajout de la synchro entre la section visible et l'élément de menu actif

---

_includes/header.html
assets/styles/accueil.scss
index.html
scripts/service.js

Corrige des défauts sur le site

---

assets/styles/site.scss
nis2.html

- taille du bagde Bêta
- texte de l’entête NIS2

Apporte encore des petites corrections

---

_includes/footer.html
assets/styles/site.scss

Enrichis le pied de page

---

_ressources/avis-bulletin.md
_ressources/cnil-ensemble.md
_ressources/cnil-reco.md
_ressources/cyber-13questions.md
_ressources/cyber-dico.md
_ressources/cyber-enjeux.md
_ressources/cybermalveillance.md
_ressources/ebios.md
_ressources/guides-gestion-crise.md
_ressources/guides-hygiene.md
_ressources/guides-remediation.md
_ressources/malette-cyber.md
_ressources/nl-industrie.md
_ressources/panorama.md
_ressources/prestas-ebios.md
_ressources/publications.md
_ressources/rapport-menace.md
_ressources/revue-presse.md
_ressources/risques-cyber.md
_ressources/secnumedu.md
_ressources/secnumedufc.md
_ressources/visa-secu.md
lib-svelte/src/catalogue/Catalogue.types.ts
lib-svelte/src/catalogue/FiltreTypologieEtFormat.svelte
lib-svelte/src/catalogue/stores/rechercheParSource.store.ts
lib-svelte/test/catalogue/stores/catalogueFiltre.store.spec.ts
lib-svelte/test/catalogue/stores/nombreResultats.store.spec.ts
lib-svelte/test/catalogue/stores/objetsExemples.ts
lib-svelte/test/catalogue/stores/rechercheParSource.store.spec.ts

- Ne retourne pas les items purement ANSSI lorsqu’une source secondaire est sélectionnée
- Change les filtres sur les ressources

Modifie le fonctionnement des filtres

---

assets/styles/site.scss

Corrige la barre de navigation et l’entête

---

_data/nis2.yml
_data/parcours-approfondir.yml
_includes/action-parcours-avec-items.html
_includes/carte-item.html
_ressources/risques-cyber.md
assets/styles/site.scss
index.html

...sur les fiches produits dans les parcours

Permets d’ajouter des tags spécifiques

---

lib-svelte/src/catalogue/stores/rechercheParFormat.store.ts

...afin de tous les sélectionner pour filtrer sur toutes les ressources

Utilise les nouveaux formats de ressources

---

_includes/header.html

Indique que le site respecte le DSFR

---

assets/styles/accueil.scss
assets/styles/site.scss
lib-svelte/src/catalogue/CarteItem.svelte
lib-svelte/src/catalogue/ExtraitItems.svelte
lib-svelte/src/test-maturite/SelectSecteurActivite.svelte

- bords noirs au survol des boutons
- augmente la limite du nombre de caractères de la description des produits
- [ACCUEIL] supprime le texte sous la barre des besoins
- liste des secteurs de la NAF
- diminue la taille de la police de la barre de navigation

Corrige des défauts visuels

---

.prettierrc.json
back/src/api/adaptateurOIDC.ts
back/src/api/configurationServeur.ts
back/src/api/fournisseurChemin.ts
back/src/api/middleware.ts
back/src/api/msc.ts
back/src/api/ressourceConnexionOIDC.ts
back/src/api/ressourcePageProduit.ts
back/src/api/ressourcePagesJekyll.ts
back/src/infra/adaptateurEnvironnement.ts
back/src/serveur.ts
back/tests/api/cookie.ts
back/tests/api/fauxObjets.ts
back/tests/api/middleware.spec.ts
back/tests/api/ressourceConnexionOIDC.spec.ts
back/tests/api/ressourcePageProduit.spec.ts
back/tests/api/ressourcePagesJekyll.spec.ts

... pour partager les mêmes règles de formatage entre nous et avec MSS

Ajoute la configuration prettier

---

.env.template
front/Gemfile
front/Gemfile.lock
front/_config.yml
front/_includes/script-matomo.html
front/_layouts/defaut.html
package.json

... afin d'ajouter du tracking utilisateur.

Ajoute la configuration de Matomo

---

LICENSE

... car c'est préconisé, est nécessaire pour nos pages statiques.

Ajoute un fichier de license Apache 2.0

---

.env.template
Dockerfile
README.md
back/knexfile.ts
back/migrations/20250306110943_creeTableUtilisateurs.ts
back/package-lock.json
back/package.json
back/src/api/configurationServeur.ts
back/src/api/msc.ts
back/src/api/oidc/ressourceApresAuthentificationOIDC.ts
back/src/infra/entrepotUtilisateurPostgres.ts
back/src/infra/utilisateurBDD.ts
back/src/metier/entrepotUtilisateur.ts
back/src/metier/utilisateur.ts
back/src/serveur.ts
back/tests/api/fauxObjets.ts
back/tests/api/oidc/ressourceApresAuthentificationOIDC.spec.ts
back/tests/api/oidc/ressourceApresDeconnexionOIDC.spec.ts
back/tests/api/oidc/ressourceConnexionOIDC.spec.ts
back/tests/api/oidc/ressourceDeconnexionOIDC.spec.ts
back/tests/api/ressourcePageProduit.spec.ts
back/tests/api/ressourcePagesJekyll.spec.ts
back/tests/api/ressourceProfil.spec.ts
back/tests/persistance/entrepotUtilisateurMemoire.ts
docker-compose.yml
front/creation-compte.html
package.json

On ajoute une base de données Postgres avec une table pour stocker les informations des utilisateurs lors de la création de compte.

Permet de sauvegarder un utilisateur

---

.env.template
Dockerfile
README.md
docker-compose.yml
package.json

... afin de corriger le déploiement dans clever et de pouvoir reproduire la construction de l’image en local

Ajoute l’application dans docker-compose

---

back/tests/api/oidc/ressourceApresAuthentificationOIDC.spec.ts
back/tests/api/oidc/ressourceConnexionOIDC.spec.ts
back/tests/api/oidc/ressourceDeconnexionOIDC.spec.ts
back/tests/api/ressourceAnnuaireDepartements.spec.ts
back/tests/api/ressourceAnnuaireOrganisations.spec.ts
back/tests/api/ressourcePagesJekyll.spec.ts

...Rajoute les configurations de serveurs de tests manquantes pour uniformiser l'usage dans les tesst

[SOIN] Utilise la configuration de test du serveur

---

.env.template
Dockerfile
back/package-lock.json
back/package.json
back/src/api/configurationServeur.ts
back/src/api/msc.ts
back/src/infra/adaptateurEnvironnement.ts
back/src/infra/adaptateurGestionErreurSentry.ts
back/src/infra/adaptateurGestionErreurVide.ts
back/src/serveur.ts
back/tests/api/fauxObjets.ts
front/_layouts/defaut.html
front/scripts/sentry.js

... afin de monitorer nos erreurs.
> [!NOTE]
> :heavy_check_mark:  Il faut valoriser les variables d'environnement  `SENTRY_DSN`, `SENTRY_ENVIRONNEMENT` lors de la mise en production. Aussi, il faut valoriser `SENTRY_AUTH_TOKEN` et `SENTRY_PROJET` UNIQUEMENT en Production afin d'uploader les source map du Svelte.

Ajoute Sentry

---

front/_layouts/service.html
front/assets/styles/catalogue.scss
front/lib-svelte/src/catalogue/CarteItem.svelte

... afin de pouvoir les utiliser dans les events de tracking.

Ajoute des `data-attribute` pour Matomo

---

back/src/api/msc.ts
front/_layouts/service.html
front/_services/mon-aide-cyber.md
front/_services/mon-service-securise.md
front/scripts/service.js

... en autorisant uniquement les vidéos provenant de notre S3.

[CORRECTION]] Corrige les CSP des vidéos

---

back/src/api/msc.ts
back/src/api/ressourceAnnuaireRegions.ts
back/src/api/ressourceAnnuaireSecteursActivite.ts
back/src/api/ressourceAnnuaireTranchesEffectif.ts
back/src/api/ressourceResultatDeTest.ts
back/src/bus/testRealise.ts
back/src/metier/referentielRegions.ts
back/src/metier/referentielSecteurs.ts
back/src/metier/referentielTranchesEffectifEtablissement.ts
back/tests/api/ressourceAnnuaireRegions.spec.ts
back/tests/api/ressourceAnnuaireSecteursActivite.spec.ts
back/tests/api/ressourceAnnuaireTranchesEffectif.spec.ts
back/tests/api/ressourceResultatDeTest.spec.ts
front/lib-svelte/src/test-maturite/SelectRegion.svelte
front/lib-svelte/src/test-maturite/SelectSecteurActivite.svelte
front/lib-svelte/src/test-maturite/SelectTailleOrganisation.svelte
front/lib-svelte/src/test-maturite/TestMaturite.donnees.ts

... pour les secteurs, régions et tranches d'effectif d'établissement

[SOIN] Extrais des ressources d'annuaire

---

.env.template
back/src/infra/adaptateurProfilAnssi.ts
back/src/infra/entrepotUtilisateurMPAPostgres.ts
back/src/infra/entrepotUtilisateurPostgres.ts
back/src/metier/utilisateur.ts
back/src/serveur.ts

... et met à jour l'utilisateur dans [MonProfilAnssi](https://github.com/betagouv/mon-profil-anssi) lors de la création de compte.

Ajoute la connexion MonProfilAnssi lors de la création de compte 

---

back/src/api/msc.ts
front/_services/mon-aide-cyber.md

Mets à jour les CSP pour embarquer le cellar de MonAideCyber

Modifie l’URL de la vidéo de présentation ainsi que celle du service

---

back/src/metier/referentielRegions.ts

...pour les Collectivités d'Outre-Mer

Ajoute une entrée au référentiel des régions

---

back/src/api/configurationServeur.ts
back/src/api/ressourceInformationsCreationCompte.ts
back/src/api/ressourceUtilisateurs.ts
back/src/infra/adaptateurProfilAnssi.ts
back/src/infra/entrepotUtilisateurMPAPostgres.ts
back/src/metier/utilisateur.ts
back/src/serveur.ts
back/tests/api/fauxObjets.ts
back/tests/api/ressourceInformationsCreationCompte.spec.ts
back/tests/api/ressourceUtilisateurs.spec.ts
front/lib-svelte/src/creation-compte/CreationCompte.svelte
front/lib-svelte/src/creation-compte/creationCompte.d.ts

pour préremplir la page de création de compte

Charge le profil de l'utilisateur depuis MPA

---

front/_includes/header.html
front/assets/styles/site.scss
front/lib-svelte/src/identification/ZoneIdentification.svelte
front/scripts/navigation-mobile.js

... Corrige aussi quelques éléments visuels ainsi que l'affichage des sélecteurs de la page /niveaux-maturite qui se retrouvaient au dessus du contenu du menu mobile.

Ajoute la zone d'identification dans le menu mobile

---

back/src/infra/adaptateurProfilAnssi.ts
back/src/infra/adaptateurProfilAnssiVide.ts

... pour les tests et faciliter les développements en local.

Ajoute un faux adaptateur MonProfilAnssi

---

back/src/api/middleware.ts
back/src/serveur.ts
back/tests/api/fauxObjets.ts
back/tests/api/middleware.spec.ts

... afin de récupérer les infos utilisateurs dans le jeton directement

Ajoute au middleware un adaptateur JWT 

---

back/src/api/msc.ts
back/src/api/ressourceDernierResultatDeTest.ts
back/src/api/ressourcePagesJekyllConnectees.ts
back/src/infra/entrepotResultatTestPostgres.ts
back/src/metier/entrepotResultatTest.ts
back/tests/api/ressourceDernierResultatDeTest.spec.ts
back/tests/api/ressourcePagesJekyllConnectees.spec.ts
front/assets/styles/test-maturite.scss
front/lib-svelte/src/main-maturite-utilisateur.ts
front/lib-svelte/src/test-maturite/MaturiteUtilisateur.svelte
front/lib-svelte/src/test-maturite/RadarMaturite.svelte
front/lib-svelte/src/test-maturite/ResultatsTestMaturite.svelte
front/lib-svelte/src/test-maturite/TestMaturite.donnees.ts
front/lib-svelte/src/test-maturite/TestMaturite.svelte
front/lib-svelte/src/test-maturite/stores/questionnaire.store.ts
front/lib-svelte/test/test-maturite/stores/questionnaire.store.spec.ts
front/lib-svelte/vite.config.ts
front/ma-maturite.html

Via une page /ma-maturité qui : 
- n’affiche pas l’encart promotionnel vers l’espace connecté MSC
- affiche un rappel des réponses données pendant le test

Affiche le dernier test de maturité de l’utilisateur connecté

---

front/_ressources/risques-cyber.md

Ajoute le lien vers la vidéo des risques

---

front/lib-svelte/package-lock.json
front/lib-svelte/package.json
front/lib-svelte/src/stores/profil.store.ts
front/lib-svelte/src/test-maturite/ResultatsTestMaturite.svelte
front/lib-svelte/src/test-maturite/TestMaturite.svelte
front/lib-svelte/src/test-maturite/resultatTest.ts
front/lib-svelte/vitest.config.js

Lorsque l’utilisateur réalise un test de maturité sans être connecté, l’identifiant est enregistré dans le stockage local. Lorsque l’utilisateur se connecte, la propriété de ce résultat est revendiquée.

Revendique la propriété d’un résultat de test

---

front/lib-svelte/src/test-maturite/PubliciteMesServicesCyber.svelte

...depuis la page résultat de test

Redirige l'utilisateur vers la page de connexion

---

front/lib-svelte/src/navigation/NavigationBureau.svelte
front/lib-svelte/src/navigation/NavigationMobile.svelte

... car les liens sont différents pour un utilisateur connecté.

Ajoute la navigation en mode "connecté"

---

front/lib-svelte/src/centre-aide/CentreAide.svelte

centre-aide-modif

---

front/_includes/header.html
front/assets/styles/site.scss

... car l'application n'est plus "Bêta"

Retire le tag "Bêta" du header

---

.env.template
back/src/api/ressourceUtilisateurs.ts
back/src/bus/cablage.ts
back/src/bus/compteCree.ts
back/src/bus/envoieEmailCreationCompte.ts
back/src/infra/adaptateurEmailBrevo.ts
back/src/infra/adaptateurEmailConsole.ts
back/src/metier/adaptateurEmail.ts
back/src/serveur.ts
back/tests/api/ressourceUtilisateurs.spec.ts
back/tests/bus/envoieEmailCreationCompte.spec.ts

... via un adaptateur Brevo.
> [!CAUTION]
> Il faut valoriser les variables `BREVO_API_URL_BASE`, `BREVO_CLE_API` et `BREVO_ID_TEMPLATE_BIENVENUE` avant la MEP

Envoi un email de bienvenue lors de la création de compte

---

front/_data/catalogue.yml
front/_data/parcours-debuter.yml

...dans les parcours et dans le catalogue. Suite au changement de typologie de cet item.

Corrige la typologie du `Label ExpertCyber` 

---

front/lib-svelte/src/favoris/MesFavoris.svelte

Modifie le texte sous l'image dans la page de favoris vide

---

front/_layouts/service.html
front/assets/styles/site.scss
front/lib-svelte/src/catalogue/CarteItem.svelte
front/lib-svelte/src/favoris/BoutonFavori.svelte
front/lib-svelte/src/main-bouton-favori.ts
front/lib-svelte/vite.config.ts

Ajoute le bouton favori dans les page produit de type "service“ 

---

front/lib-svelte/src/creation-compte/CreationCompte.svelte

[CORRECTION] Corrige le format de la case à cocher pour qu'elles soient identiques

---

front/assets/styles/test-maturite.scss
front/lib-svelte/src/test-maturite/PubliciteMesServicesCyber.svelte

Retire une carte d'information dans le résultat de test de maturité

---

front/assets/styles/catalogue.scss
front/lib-svelte/src/catalogue/CarteItem.svelte
front/lib-svelte/src/favoris/BoutonFavori.svelte

... L'idée est de temporairement donner l'information au utilisateurs simplement.

Affiche le bouton favori en mode non connecté et ajoute un titre comme tooltip

---

front/_services/diagnostic-17cyber.md

...en fusionnant les badges pour gagner de la place

Corrige la hauteur de la carte 17cyber

---

front/assets/styles/test-maturite.scss
front/lib-svelte/src/test-maturite/ResultatsTestMaturite.svelte
front/lib-svelte/src/ui/ConteneurOnglets.svelte
front/lib-svelte/src/ui/Onglet.svelte

... permettant d’accéder à la comparaison qui contient une annonce sur la disponibilité prochaine de cette fonctionnalité

[MATURITE] Affiche des onglets

---

back/src/api/middleware.ts
back/src/api/msc.ts
back/src/api/oidc/ressourceApresAuthentificationOIDC.ts
back/src/api/ressourcePageConnexion.ts
back/src/api/ressourcePageProduit.ts
back/src/api/ressourcePagesJekyll.ts
back/src/api/ressourcePagesJekyllConnectees.ts
back/src/express.d.ts
back/tests/api/middleware.spec.ts
back/tests/ressources/factice.html
front/_layouts/defaut.html

Afin de préparer l’ajout de l’UI kit qui a besoin du nonce.

Enrichis les pages avec le nonce

---

back/tests/api/fauxObjets.ts

...en ajoutant les fonctions de middleware

Corrige les faux objets

---

front/_layouts/defaut.html

... Utilise la dernière version de l'ui kit suite à des décisions métiers.

Met à jour la version de l'ui kit

---

front/lib-svelte/src/favoris/BoutonFavori.svelte

...suite à la suppression d’une erreur eslint.

Corrige visuellement le comportement du bouton favori

---

front/lib-svelte/src/favoris/BoutonFavori.svelte

...en supprimant une fonction inutile

[SOIN] Corrige une erreur lint

---

docker-compose.yml

… afin que Docker sache qu'il doit lancer la BDD quand on lance l'app.

Indique que l'app dépend de la BDD

---

back/admin/consoleAdministration.ts
back/src/api/ressourceUtilisateurs.ts
back/src/bus/cablage.ts
back/src/bus/compteCree.ts
back/src/bus/creeContactBrevo.ts
back/src/infra/adaptateurEmailBrevo.ts
back/src/infra/adaptateurEmailConsole.ts
back/src/infra/entrepotUtilisateurMPAPostgres.ts
back/src/metier/adaptateurEmail.ts
back/src/metier/entrepotUtilisateur.ts
back/tests/api/ressourceUtilisateurs.spec.ts
back/tests/bus/creeContactBrevo.spec.ts
back/tests/bus/envoieEmailCreationCompte.spec.ts

Cela ajoute aussi une console d'administration avec une méthode pour faire le rattrapage des utilisateurs qui n'ont pas été ajouté en contact dans Brevo.

Ajoute la création de contact dans Brevo lors de la création de compte l'utilisateur

---

back/package.json
back/src/infra/adaptateurEmailBrevo.ts
package-lock.json

...pour décoder les caractères HTML encodés

Corrige l’encodage des caractères envoyés à Brevo

---

back/package.json
back/src/admin/consoleAdministration.ts
back/src/api/middleware.ts
back/src/infra/entrepotUtilisateurMPAPostgres.ts
package-lock.json

En ajoutant un cadençage sur:
-  la récupération utilisateurs dans MonProfilAnssi 
- sur la récupération des utilisateurs en BDD.
En évitant de retourner un utilisateur qui n'est pas présent dans MPA.

Corrige le rattrapage de la création des contacts dans Brevo 

---

front/lib-svelte/src/demande-aide-mon-aide-cyber/ConfirmationCreationDemandeAide.svelte

Pour avoir un affichage qui reste OK, après les modifications de #276 👇

Ajuste l'affichage du bloc de confirmation

---

front/lib-svelte/src/creation-compte/CreationCompte.svelte
front/lib-svelte/src/creation-compte/creationCompte.d.ts

...qui avaient été copiés depuis MSS par erreur

Supprime des types et des propriétés inutiles

---

package.json

… pour rendre la sortie plus lisible.
Le résultat 👇

Ajoute des couleurs au `concurrently`

---

back/src/admin/consoleAdministration.ts
back/src/api/ressourceFavori.ts
back/src/api/ressourceFavoris.ts
back/src/bus/cablage.ts
back/src/bus/consigneEvenementMAJFavorisUtilisateurDansJournal.ts
back/src/bus/miseAJourFavorisUtilisateur.ts
back/src/infra/adaptateurJournal.ts
back/src/serveur.ts
back/tests/api/ressourceFavori.spec.ts
back/tests/api/ressourceFavoris.spec.ts
back/tests/api/ressourceFavorisPartages.spec.ts
back/tests/bus/consigneEvenementMAJFavorisUtilisateurDansJournal.spec.ts

Ajoute aussi une méthode de rattrapage de ces événements via la console d'administration.

Consigne un évènement dans le journal de la mise à jour des favoris d'un utilisateur

---

front/_layouts/defaut.html

... Utilise la dernière version de l'ui-kit qui met à disposition le composant.

[CORRECTION] Ajoute les informations PSSI sur la page de sécurité

---

front/favoris.html

...afin d'afficher les cartes correctement

[CORRECTION] Ajoute le style manquant pour la page favoris

---

front/confidentialite.html

Coucou
Il y avait un probleme de saut à la ligne + un li> qui se baladait - petit reliquat des mes PR nocturnes ;)
Merci !

petit-fix-page-PC

---

front/lib-svelte/src/navigation/NavigationBureau.svelte
front/lib-svelte/src/navigation/NavigationMobile.svelte
front/nis2.html
front/parcours-approfondir.html
front/parcours-debuter.html

Renomme "notre sélection" en "nos sélections"

---

front/_ressources/cyber-enjeux-pro.md

J'avais oublié de mettre le lien bon vers le zip cyberenjeux pro dans le CTA de la fiche !

fix-lien-cyberenjeuxpro

---

back/src/api/mon-aide-cyber/ressourceDemandesAide.ts
back/tests/api/mon-aide-cyber/ressourceDemandesAide.spec.ts
front/_includes/encart-cyberdepart.html
front/lib-svelte/src/demande-aide-mon-aide-cyber/DemandeAideMAC.svelte
front/lib-svelte/src/test-maturite/EncartDeRecommandationSelonMaturite.svelte

… car c'est le wording qu'on souhaite utiliser.

Parle d'aidant **cyber** plutôt que d'aidant tout court

---

front/_layouts/defaut.html

...afin de bénéficier de la nouvelle formulation de l’aidant cyber, à la place de l’aidant de la communauté

Monte la version de l’UI kit

---

front/_ressources/cyber-enjeux.md

Hello,
J'ai MàJ le lien de redirection de la fiche cyberenjeux + j'ai ajouté un "bloc" en bas de page pour pouvoir télécharger tous les supports (pour harmoniser avec la fiche cyberenjeux PRO)

fiche-cyberenjeux

---

front/assets/styles/accueil.scss
front/index.html

Ajoute le bloc Communauté MesServicesCyber à l'accueil

---

back/src/api/msc.ts
front/lib-svelte/src/main-session-groupe.ts
front/lib-svelte/src/test-maturite/SessionGroupe.svelte
front/lib-svelte/src/ui/ChampTexte.svelte
front/lib-svelte/vite.config.ts
front/session-groupe.html

...permettant de lancer une nouvelle session de groupe ou de rejoindre une session existante.

[SESSION DE GROUPE] Ajoute une page d’accueil 

---

front/_includes/head.html
front/assets/styles/boutons.scss
front/assets/styles/controle-segmente.scss
front/assets/styles/parcours.scss
front/nis2.html
front/parcours-approfondir.html
front/parcours-debuter.html

Nos boutons secondaires correspondaient davantage à des boutons tertiaires. 
On a aussi déplacer le style des controles segmentés dans un fichier spécifique

Corrige les styles des boutons secondaires

---

back/src/api/msc.ts
front/_layouts/defaut.html
front/assets/styles/test-maturite.scss
front/lib-svelte/src/test-maturite/OngletsTest.svelte
front/lib-svelte/src/test-maturite/TestMaturite.svelte
front/lib-svelte/src/ui/FilAriane.svelte
front/lib-svelte/src/ui/Hero.svelte
front/lib-svelte/src/ui/filAriane.ts
front/resultats-session-groupe.html

- ajout d’un bandeau 
- mise à jour du fil d’ariane avec la session de groupe
- les résultats ne sont pas envoyés mais une page de résultat est affichée. Elle sera complétée à la prochaine PR.

Adapte le test de maturité pour l’organisateur d’une session de groupe

---

back/src/api/msc.ts
back/src/api/testMaturite/ressourceResultatsSessionDeGroupe.ts
back/src/infra/EntrepotSessionDeGroupePostgres.ts
back/src/infra/entrepotResultatTestPostgres.ts
back/src/metier/entrepotResultatTest.ts
back/src/metier/resultatTestMaturite.ts
back/src/metier/sessionDeGroupe.ts
back/tests/api/testMaturite/ressourceResultatsSessionDeGroupe.spec.ts
back/tests/api/testMaturite/ressourceSessionDeGroupe.spec.ts
back/tests/metier/resultatTestMaturite.spec.ts
back/tests/metier/sessionDeGroupe.spec.ts
back/tests/persistance/entrepotResultatTestMemoire.ts
front/lib-svelte/src/test-maturite/GraphiqueAnneau.svelte
front/lib-svelte/src/test-maturite/ResultatsSessionGroupe.svelte

Calcule et affiche les résultats d’une session groupe

---

front/_layouts/defaut.html
front/lib-svelte/src/test-maturite/GraphiqueAnneau.svelte
front/lib-svelte/src/test-maturite/ModaleNouvelleSessionGroupe.svelte
front/lib-svelte/src/test-maturite/RadarSessionGroupe.svelte
front/lib-svelte/src/test-maturite/TestMaturite.svelte

- Copie du lien de participation (pour que l’organisateur puisse le partager)
- Correction de l’affichage de l’alerte (largeur, cf [PR #70 de l’UI kit)](https://github.com/betagouv/lab-anssi-ui-kit/pull/70)
- Corrige l’affichage de l’image sur la page d’introduction du test
- Apporte des informations accessibles sur le survol des graphiques (cf ci-dessous) 
Vue du survol au-dessus d’un sommet :

[SESSION GROUPE] Apporte quelques ajustements visuels 

---

front/assets/styles/test-maturite.scss
front/lib-svelte/src/test-maturite/TestMaturite.svelte

En ajoutant un lien depuis l’accueil du test de maturité :

Active les sessions de groupe

---

front/inscription.html

...suite à la suppression du layout spécifique et à l’utilisation du style générique de la page par défaut.

[CORRECTION] Corrige l’affichage de la page d’inscription

---

front/lib-svelte/src/test-maturite/TestMaturite.svelte

- reformule l’accès à la session de groupe
- numérote les propositions :

Corrige des aspects visuels du test de maturité

---

front/_layouts/defaut.html

... en passant à la version corrigée de l'ui kit

[CORRECTION] Corrige l'affichage du menu sur mobile dans Safari

---

back/src/api/ressourceProfil.ts
back/src/infra/adaptateurProfilAnssiVide.ts
back/src/infra/entrepotUtilisateurMPAPostgres.ts
back/src/metier/utilisateur.ts
back/tests/api/ressourceProfil.spec.ts
back/tests/metier/utilisateur.spec.ts
front/_includes/header.html
front/assets/styles/site.scss
front/lib-svelte/src/badge-agent-anssi/BadgeAgentAnssi.svelte
front/lib-svelte/src/main-badge-agent-anssi.ts
front/lib-svelte/src/stores/profil.store.ts
front/lib-svelte/vite.config.ts

Affiche un badge pour les agents ANSSI

---

front/assets/styles/site.scss

Corrige les marges de l’entête en mode bureau

---

front/index.html

Modifie un CTA de la page d'accueil

---

front/_services/mon-aide-cyber.md
front/lib-svelte/src/demande-aide-mon-aide-cyber/DemandeAideMAC.svelte

dans la demande de diag (et fiche produit) on disait que le diag n'était pas pour les micro entreprises, en fait c'est entreprises mono salariées

Remplace la micro-entreprise par les entreprises mono-salariées

---

front/parcours-debuter.html

… qui pointait par erreur vers la page NIS2

[CORRECTION] Corrige le lien vers la demande de diagnostic cyber

---

.env.template
back/src/api/configurationServeur.ts
back/src/api/msc.ts
back/src/api/ressourceRetoursExperience.ts
back/src/infra/messagerieMattermost.ts
back/src/metier/messagerieInstantanee.ts
back/src/serveur.ts
back/tests/api/fauxObjets.ts
back/tests/api/ressourceRetoursExperience.spec.ts
front/_layouts/defaut.html
front/lib-svelte/src/demande-aide-mon-aide-cyber/DemandeAideMAC.svelte
front/lib-svelte/src/demande-aide-mon-aide-cyber/DialogueSortieDiagnostic.svelte
front/lib-svelte/src/test-maturite/ModaleNouvelleSessionGroupe.svelte
front/lib-svelte/src/ui/BoutonFermerModale.svelte
front/lib-svelte/src/ui/ChampTexte.svelte
front/lib-svelte/src/ui/ZoneTexte.svelte

Affiche une boîte de dialogue à l’utilisateur qui s’apprête à quitter le diagnostic cyberdépart avant d’avoir terminé. L’objectif est de recueillir les raisons pour lesquelles il ne termine pas sa demande.

[DIAGNOSTIC] Dialogue de sortie

---

front/_layouts/defaut.html
front/lib-svelte/src/demande-aide-mon-aide-cyber/DialogueSortieDiagnostic.svelte
front/lib-svelte/src/ui/BoutonFermerModale.svelte

Apporte les corrections imperfections visuelles detectée lors de la recette :
- Taille des titres de sections agrandie
- Rendu des boutons du formulaire corrigé (bordure, padding et taille)
- Taille des titres de modale agrandie en tablette & desktop (rendu mobile inchangé)
Bonus :
- Ajout d'une transition à l'ouverture de la modale
- Utilise le nouveau composant Bouton de l'UI KIT pour afficher les boutons de fermeture de modale

[DIAG] Modale sortie retours recette

---

back/src/api/middleware.ts

Autorise les médias en provenance du cellar MSC

---

front/lib-svelte/src/statistiques/Statistiques.svelte

- libellés des niveaux de maturité
- centrage du graphique
- taille du titre en mode bureau
- pluriel sur les « Tests »

Apporte quelques retouches à la page statistiques

---

back/src/api/testMaturite/ressourceResultatsDeTest.ts
back/src/infra/entrepotResultatTestPostgres.ts
back/src/metier/entrepotResultatTest.ts
back/src/metier/resultatTestMaturite.ts
back/tests/api/testMaturite/ressourceResultatsDeTest.spec.ts
back/tests/persistance/entrepotResultatTestMemoire.ts
front/lib-svelte/src/test-maturite/CarteTestMaturite.svelte
front/lib-svelte/src/test-maturite/HistoriqueTests.svelte
front/lib-svelte/src/test-maturite/OngletsTest.svelte
front/lib-svelte/src/test-maturite/PropositionRefaireTest.svelte
front/lib-svelte/src/test-maturite/ResultatsMonOrganisation.svelte
front/lib-svelte/src/test-maturite/ResultatsTestMaturite.svelte
front/lib-svelte/src/ui/ConteneurOnglets.svelte

Affiche l'historique des tests dans un nouvel onglet pour l'utilisateur connecté

Affiche l’historique des tests de maturité

---

front/lib-svelte/src/test-maturite/HistoriqueTests.svelte

- Tri des résultats
- Regroupe par année

Enrichis l'affichage de l'historique

---

back/src/api/testMaturite/ressourceResultatsDeTest.ts
back/tests/api/testMaturite/ressourceResultatsDeTest.spec.ts
front/lib-svelte/src/test-maturite/CarteTestMaturite.svelte
front/lib-svelte/src/test-maturite/HistoriqueTests.svelte
front/lib-svelte/src/test-maturite/MaturiteUtilisateur.svelte
front/lib-svelte/src/test-maturite/ResultatsMonOrganisation.svelte
front/lib-svelte/src/test-maturite/ResultatsSessionGroupe.svelte
front/lib-svelte/src/test-maturite/ResultatsTestMaturite.svelte
front/lib-svelte/src/test-maturite/Serie.ts
front/lib-svelte/src/test-maturite/TestMaturite.donnees.ts
front/lib-svelte/src/test-maturite/stores/questionnaire.store.ts

Affiche les résultats d'ancien test depuis l'onglet historique

---

front/lib-svelte/src/test-maturite/CarteTestMaturite.svelte

...à l’aide d’une transformation d’échelle des images

[HISTORIQUE] Corrige la taille des illustrations des niveaux

---

back/src/api/testMaturite/ressourceDernierResultatDeTest.ts
back/tests/api/testMaturite/ressourceDernierResultatDeTest.spec.ts
front/lib-svelte/src/test-maturite/MaturiteUtilisateur.svelte
front/lib-svelte/src/test-maturite/ResultatsTestMaturite.svelte

Affiche la date de réalisation du dernier test

---

front/lib-svelte/src/test-maturite/ComparaisonTest.svelte
front/lib-svelte/src/test-maturite/RadarSessionGroupe.svelte

Adapte les libellés du radar de comparaison en mobile

---

front/index.html
front/lib-svelte/src/test-maturite/PubliciteMesServicesCyber.svelte

...qui indique que la comparaison sera bientôt disponible, sur la page d’accueil et dans le résultat du test. 
Elle l’est.

Supprime la mention « À venir »

---

back/src/api/testMaturite/ressourceResultatDeTest.ts
back/src/api/testMaturite/ressourceResultatsDeTest.ts
back/src/infra/entrepotResultatTestPostgres.ts
back/src/metier/resultatTestMaturite.ts
back/tests/api/objetsPretsALEmploi.ts
back/tests/api/ressourceStatistiques.spec.ts
back/tests/api/testMaturite/ressourceDernierResultatDeTest.spec.ts
back/tests/api/testMaturite/ressourceRepartitionDesResultatsDeTest.spec.ts
back/tests/api/testMaturite/ressourceResultatDeTest.spec.ts
back/tests/api/testMaturite/ressourceResultatsDeTest.spec.ts
back/tests/api/testMaturite/ressourceResultatsSessionDeGroupe.spec.ts
back/tests/metier/resultatTestMaturite.spec.ts
back/tests/metier/sessionDeGroupe.spec.ts
back/tests/persistance/entrepotResultatTestMemoire.ts

... si l'utilisateur n'a pas saisi les informations à l'étape 7

Revendique avec details organisation

---

back/package.json
back/tests/api/ressourcePageCrisp.spec.ts
back/tests/mockCmsCrisp.ts
package-lock.json

...afin de résoudre un problème d'import de module commonjs

Monte la version de la dépendance lab-anssi

---

front/lib-svelte/src/test-maturite/GraphiqueAnneau.svelte

...car la fonction ne semble pas être réactive

Rends réactif les secteurs de l’anneau

---

front/lib-svelte/src/test-maturite/ComparaisonTest.svelte
front/lib-svelte/src/test-maturite/ResumeRadarComparaison.svelte
front/lib-svelte/src/ui/ConteneurOnglets.svelte

|Bordures onglets|Séparateur|Légende Radar|
|-|-|-|
|<img width="860" height="164" alt="image" src="https://github.com/user-attachments/assets/04048f83-5613-4ec6-b6b0-c8a74322575f" />|<img width="894" height="237" alt="image" src="https://github.com/user-attachments/assets/45486f4f-0e42-4af7-8a72-0913da0abbb3" />|<img width="879" height="285" alt="image" src="https://github.com/user-attachments/assets/ee03b326-32a9-41dd-827d-a56dba16dd9d" />|

[COMPARAISON] Retour recette comparaison

---

front/assets/styles/site.scss
front/lib-svelte/src/demande-aide-mon-aide-cyber/DemandeAideMAC.svelte
front/lib-svelte/src/test-maturite/ResumeRadarComparaison.svelte
front/lib-svelte/src/ui/SectionAccordeon.svelte

[PAGE CYBERDEPART] Ajoute la FAQ

---

front/lib-svelte/src/demande-aide-mon-aide-cyber/DemandeAideMAC.svelte

Coucou,
Vu avec Nico et les bizdev on a modifié le wording de mise en avant du webinaire sur le formulaire de demande de diag

[PAGE CYBERDEPART] modifie le texte pour le webinaire cyberdepart

---

front/_layouts/defaut.html

...afin de bénéficier de la correction du centrage du contenu des boutons et des liens qui en ont l’apparence

Bascule sur la dernière version de l’ui kit

---

front/_layouts/defaut.html
front/assets/styles/site.scss
front/lib-svelte/src/avis-utilisateur/AvisUtilisateur.svelte
front/lib-svelte/src/ui/ZoneTexte.svelte

Visuel :
|Etat initial|Validation|
|-|-|
|<img width="636" height="676" alt="image" src="https://github.com/user-attachments/assets/7e38790c-f993-4b96-958d-efaa324f1cc8" />|<img width="631" height="734" alt="image" src="https://github.com/user-attachments/assets/dca3efdf-9292-4bcf-a333-fe6aa86aa31f" />|

[FEEDBACK] Dialogue avis utilisateur

---

front/lib-svelte/src/statistiques/Statistiques.svelte

...notamment la partie "Répartition de la maturité cyber"

[STATISTIQUES] Retravaille le visuel de la page statistiques

---

back/src/api/msc.ts
front/assets/styles/carte-item.scss
front/assets/styles/prestataires-qualifies.scss
front/prestataires.html

 [PRESTAS] Crée la page des prestataires qualifiés

---

front/assets/styles/prestataires-qualifies.scss

...sur la page des prestataires

[CORRECTION] Surcharge le style des labels

---

front/assets/styles/page-statique.scss
front/assets/styles/site.scss
front/lib-svelte/src/financements/SectionDetailsFinancement.svelte
front/lib-svelte/src/test-maturite/ModaleNouvelleSessionGroupe.svelte

...pour les navigateurs basés sur webkit (.e.g Safari)

[CORRECTION] Applique un style souligné aux liens

---

front/_data/catalogue.yml
front/lib-svelte/src/catalogue/Catalogue.types.ts
front/lib-svelte/src/catalogue/FiltreSource.svelte
front/lib-svelte/src/catalogue/stores/nombreResultats.store.ts
front/lib-svelte/src/catalogue/stores/rechercheParSource.store.ts
front/lib-svelte/test/catalogue/stores/nombreResultats.store.spec.ts
front/lib-svelte/test/catalogue/stores/rechercheParSource.store.spec.ts

Corrige un problème sur le nombre de publication, à cause d’une erreur de référencement dans le catalogue.
Améliore le filtre sur les sources, en ajoutant une entrée spécifique pour les items ANSSI qui n’ont pas de source secondaire :

[BUG] Corrige et améliore les filtres

---

front/lib-svelte/src/navigation/NavigationBureau.svelte
front/lib-svelte/src/navigation/NavigationMobile.svelte

...en 'Le catalogue cyber complet'

[NAVIGATION] Renomme l'entrée 'Catalogue'

---

front/lib-svelte/src/demande-aide-mon-aide-cyber/DemandeAideMAC.svelte
front/lib-svelte/src/demande-aide-mon-aide-cyber/FormulaireDemandeAide.svelte

...afin de rendre la remontée de metriques plus fiable

[CORRECTION] Identifie le formulaire de demande de diag

---

front/lib-svelte/src/niveaux-maturite/NiveauxMaturite.svelte

sur cette page : https://messervices.cyber.gouv.fr/niveaux-maturite il y avait une coquille sur "resources"

corrige une coquille sur la page des niveaux de maturité

---

front/_services/mon-espace-nis2.md

retour de la com' interne ANSSI

modifie le titre de la carte MENIS2
