_layouts/service.html
_ressources/demain-specialiste-cyber.md
_ressources/livret-cyber-enjeux.md
_services/mon-aide-cyber.md
_services/mon-service-securise.md
assets/styles/catalogue.scss
assets/styles/site.scss
catalogue.html
lib-catalogue/src/CarteItem.svelte

Cette PR change le look des cartes, et les anime au survol.
La mention verte disparaît, et le violet est soit un picto de lien interne soit un picto de lien interne 👇 
Résultat 👇 
Au survol, les illustrations se soulèvent de `8px` et on a une couleur de fond 👇

Anime les cartes sur le catalogue et la page service

---

assets/styles/catalogue.scss
lib-catalogue/src/FiltreTypologieEtFormat.svelte

...suite à la recette :
- mot « PDF » dans la mauvaise casse
- pointeur sur les cases à cocher
- espace entre le titre et le sous-titre

Corrige des défauts visuels

---

lib-catalogue/src/stores/rechercheParSource.store.ts
lib-catalogue/test/stores/rechercheParSource.store.spec.ts

- le filtre source reste robuste lorsque certains items n’ont pas de source

Corrige les filtres suite à l’ajout de nouveaux items

---

_layouts/test-maturite.html

Afin que le partage LinkedIn lise correctement l’image

Corrige l’adresse de l’image dans les balises meta

---

.github/workflows/integration-continue.yml
.gitignore
404.html
Dockerfile
_config.yml
package-lock.json
package.json
src/serveur.ts
src/tsconfig.json

Pour préparer l’API qui va notamment s’occuper de l’authentification, nous servons désormais le site via un backend express qui tourne sur Node. 
L’objectif est donc :
- mettre en place ce backend
- servir toutes les ressources du site via ce backend
- adapter le Dockerfile pour construire et servir ce backend
- avoir un environnement de développement quasiment identique à celui fourni par jekyll (sans le livereload pour l’instant)

Ajoute backend express

---

Dockerfile

...en copiant le fichier package.json qui se situe à la racine

Corrige le lancement de l’image docker

---

package-lock.json
package.json

Grace à l'ajout d'un script npm, on peut lancer l'installation des dépendances des 3 projets imbriqués directement afin de faciliter l'installation. De plus, nous en avons profiter pour faire du nettoyage dans les dépendances du projet racine.

Améliore l'installation des dépendances 

---

Dockerfile
README.md

... afin de construire correctement le site avec Jekyll, et dans notre cas, en activant ou non Matomo.

Utilise les variables `--build-arg` passées dans le Dockerfile

---

front/_layouts/defaut.html

... car la structure des variables d'environnement diffère entre un developpement local et un déploiement.

[CORRECTION] Prend en compte les variables d'environnement vide

---

package.json

... Nous avons ajouter un script de migration spécifique pour le contexte de déploiement car il n'a pas de fichier .env dans Clever Cloud les variables d'environnement sont injectées directement

Corrige le déploiement Clever

---

package.json

... On corrige le chemin relatif vers les fichiers pour l'ORM knex, les dépendances et les fichiers de configurations sont copiés à la racine dans le Dockerfile

Corrige le script pour lancer la migration knex dans le déploiement

---

.env.template
back/package-lock.json
back/package.json
back/src/api/middleware.ts
back/src/api/msc.ts
back/tests/api/middleware.spec.ts

On utilise [Helmet](https://helmetjs.github.io/) pour obtenir une configuration de base de sécurité.
On rajoute :
- Une politique de `no-cache` au global
- Une politique de "Cache" sur les fichiers statiques afin de garder de la fluidité sur les assets du site.
> [!CAUTION]
> Il faut valoriser la variable d'env. `CACHE_CONTROL_FICHIERS_STATIQUES` au moment de la mise en production

Ajoute des headers de sécurité

---

front/assets/styles/site.scss

... car le font par défaut est différent selon les navigateurs.

[CORRECTION] Applique le font "Marianne" sur les "select"

---

back/src/api/msc.ts
docker-compose.yml

On considère que le service est exposé derrière deux reverse proxies. On doit mettre trust proxy à 2 dans ce cas.
Cf. https://expressjs.com/en/guide/behind-proxies.html
Aussi, on log, provisoirement, les en-tête HTTP reçu pour valider sur chaque environnement les en-têtes positionnés par les proxies.

Appliquer le rate-limit dans le contexte d'un reverse proxy 2

---

.env.template
back/src/api/configurationServeur.ts
back/src/api/msc.ts
back/src/infra/adaptateurEnvironnement.ts
back/src/serveur.ts

`trust proxy` est rendu paramétrable pour s'adapter à l'environnement.
Cf. https://expressjs.com/en/guide/behind-proxies.html
Aussi, on supprime le log des en-tête HTTP reçus qu'on avait mis en place provisoirement.

Rate limit proxy paramétrable

---

package.json

... car il manquait l'utilisation de `tsx`

[CORRECTION] Corrige le lancement des migrations en local

---

.env.template
back/src/api/configurationServeur.ts
back/src/api/msc.ts
back/src/infra/adaptateurEnvironnement.ts
back/src/serveur.ts

Pour éviter les difficultés de paramétrage, on applique la même limite sur le nombre de requêtes par minutes sur toutes les pages du service.
On fixe cette limite, par défaut, à 600 mais cela est paramétrable.

Simplifier la gestion du nombre maximum de requêtes par minute

---

front/assets/styles/accueil.scss
front/assets/styles/catalogue.scss
front/assets/styles/connexion.scss
front/assets/styles/niveaux-maturite.scss
front/assets/styles/page-statique.scss
front/assets/styles/parcours.scss
front/assets/styles/responsive.scss
front/assets/styles/service.scss
front/assets/styles/site.scss
front/assets/styles/test-maturite.scss
front/lib-svelte/src/creation-compte/CreationCompte.svelte
front/lib-svelte/src/ui/Etapier.svelte
front/lib-svelte/vite.config.ts

... Ceci permet de corriger la majorité des alertes remontant au lancement du script de développement et qui pollue les logs et rends leurs lectures compliqués. De plus il s'agit principalement de dépréciation Scss lié à la mise à jour vers [Dart 3.0 ](https://sass-lang.com/dart-sass/)

Résout les alertes de compilation lié à des dépréciations 

---

back/src/api/middleware.ts
back/tests/api/middleware.spec.ts

...il faut faire un `send` pour envoyer la réponse

Corrige l’envoi du statut lors de la vérification JWT

---

.env.template
.gitignore
back/package-lock.json
back/package.json
back/src/api/configurationServeur.ts
back/src/api/msc.ts
back/src/infra/adaptateurEnvironnement.ts
back/src/infra/adaptateurGestionErreurSentry.ts
back/src/serveur.ts
back/tests/api/fauxObjets.ts

On permet au serveur de filtrer les IPs qui ont le droit d'effectuer des requêtes.
Si le paramètre n'est pas positionné, aucun filtrage n'a lieu.
On adapte le gestionnaire d'erreur pour retourner 401 et terminer le traitement de la requête en cas de IpDenied

Ajoute le filtrage IP

---

front/lib-svelte/src/test-maturite/MaturiteUtilisateur.svelte

…si l'utilisateur n'a pas encore de résultat.
Cela évite d'afficher un résultat de test faux et d'améliorer l'expérience utilisateur.

Redirige vers la page du test de maturité 

---

back/src/api/msc.ts

Lorsqu'on active le filtrage IP, on veut vérifier que les requêtes proviennent bien du WAF. Pour cela, on extrait la dernière IP de l'en-tête x-forwarded-for qui devrait être celle du WAF. Si ce n'est pas le cas, on rejette l'appel.
Plusieurs cas à la marge à traiter :
* x-forwarded-for peut être vide donc on vérifie que c'est une string
* la liste séparée par des virgules peut contenir des espaces donc on trim
* la liste pourrait contenir une IP vide donc on les filtre
Si on retourne une chaîne vide, IpFilter laisse passer la requête donc, par défaut, on retourne la chaîne "interdire" pour bloquer la requête.

Corrige le filtrage IP

---

front/lib-svelte/src/creation-compte/CreationCompte.svelte

...sinon, on peut générer plusieurs fois le POST entre le moment où le premier est terminé et avant le redirect

[CORRECTION] Ne réactive le bouton que si l'envoi du formulaire a échoué

---

front/_data/catalogue.yml
front/_includes/script-donnees-json.html
front/lib-svelte/src/catalogue/Catalogue.types.ts
front/lib-svelte/src/catalogue/stores/catalogue.store.ts
front/lib-svelte/src/catalogue/stores/catalogueParBesoin.ts
front/lib-svelte/test/catalogue/stores/catalogueFiltre.store.spec.ts

Les produits sont désormais triés en suivant l’ordre de tri spécifié dans le fichier catalogue.yml

Ordonne les items du catalogue sans filtre sur le besoin cyber.

---

front/lib-svelte/src/favoris/FavorisPartages.svelte

Quand l'utilisateur est connecté, on lui affiche les boutons favoris et on l'incite à aller sur le catalogue.
Quand il n'est pas connecté, on ne lui affiche pas de boutons favoris et on l'incite à créer un compte.

Différencie l'utilisateur connecté et non connecté sur les favoris partagés

---

front/lib-svelte/src/favoris/MesFavoris.svelte
front/lib-svelte/src/navigation/NavigationBureau.svelte
front/lib-svelte/src/test-maturite/ResultatsTestMaturite.svelte
front/lib-svelte/src/test-maturite/TestMaturite.svelte
front/lib-svelte/src/ui/Onglet.svelte

Lors du démarrage de l'application plusieurs scripts sont lancés en parallèle, nous avions des warnings eslint/svelte et Sass à corriger.

Corrige des warnings affiché lors de la compilation

---

front/assets/styles/service.scss
front/lib-svelte/src/creation-compte/CreationCompte.svelte

On utilise un "text-decoration underline" sur un lien au lieu d'un border-bottom pour stylise correctement et conformément au reste de l'application.
Cela évite d'avoir une effet d'espacement/clignotement au survole du lien.

Corrige les derniers liens avec le bon style

---

package-lock.json
package.json

La dépendance n'est pas utilisée (sauf au "peer dependency" de post-css pour svelte) elle peut donc être supprimée. 
Pour faciliter le test de non régression pendant le développement, j'ajoute un script pour lancer tous les tests en parallèle depuis la racine.

Supprime la dépendance Ts-node 

---

front/_includes/script-donnees-json.html
front/favoris-partages.html
front/favoris.html
front/lib-svelte/src/catalogue/stores/catalogue.store.ts
front/lib-svelte/src/main-favoris-partages.ts
front/lib-svelte/src/main-favoris.ts

La répartition des besoins est nécessaire pour l’affichage du catalogue ou de l’extrait en fonction des besoins cyber. Les favoris n’ont pas besoin de cette répartition.

[SOIN] Enlève la répartition des besoins pour les favoris

---

front/_layouts/service.html
front/_services/conseil-technique.md
front/assets/styles/site.scss

Cette PR modifie la description du service, et masque le bouton qui était un `mailto` 👇 
Ce service ne souhaite pas avoir de lien `mailto` sur sa page.

fiche-conseil-technique

---

front/_ressources/cyber-13questions.md
front/_ressources/panorama.md
front/lib-svelte/src/main-catalogue.ts
front/lib-svelte/src/main-centre-aide.ts
front/lib-svelte/src/main-contacts.ts
front/lib-svelte/src/main-creation-compte.ts
front/lib-svelte/src/main-extrait.ts
front/lib-svelte/src/main-favoris-partages.ts
front/lib-svelte/src/main-favoris.ts
front/lib-svelte/src/main-identification.ts
front/lib-svelte/src/main-maturite-utilisateur.ts
front/lib-svelte/src/main-navigation.ts
front/lib-svelte/src/main-niveaux-maturite.ts
front/lib-svelte/src/main-test-maturite.ts

- Supprime les variables parcours des ressources car la variable n'est plus utilisées.
- Supprime les export default inutiles en renvoyant implicitement le composant directement.

Applique des correctifs de dettes techniques

---

.github/workflows/checkov.yml
.github/workflows/integration-continue.yml
Dockerfile

Le CIS propose un [benchmark](https://www.cisecurity.org/benchmark/software-supply-chain-security) pour la configuration sécurisée de GitHub et [checkov](https://www.checkov.io/1.Welcome/What%20is%20Checkov.html) valide automatiquement ces règles ainsi que quelques autres.
Cette PR met ces contrôles en place sur le projet avec [checkov-action](https://github.com/bridgecrewio/checkov-action).
Cette PR intègre également les changements nécessaires pour se conformer à ces recommandations :
* diminuer les permissions des jobs CI
* ignorer la règles sur docker HEALTHCHECK dans la mesure où Clever ne s'en sert pas
* créer un utilisateur dédié à l'exécution du serveur pour éviter de tourner en root

Ajoute une vérification checkov de la configuration CI/CD

---

Dockerfile

Lorsqu'on tente de se connecter sur un conteneur sur Clever Cloud, cette infrastructure lance `bash`. Si `bash` n'est pas installé dans le conteneur, alors, il devient impossible de faire `clever ssh` en cas de besoin.

Ajoute bash

---

back/src/api/middleware.ts
back/src/serveur.ts
back/tests/api/fauxObjets.ts
back/tests/api/middleware.spec.ts
front/scripts/service.js

Correctif appliqués pour les erreurs suivantes: 
- Evite au js de casser lors de la construction du sommaire si un de ces éléments n'a pas de `textContent`
- https://sentry.incubateur.net/organizations/betagouv/issues/165743/?project=221&referrer=webhooks_plugin
- Ajoute une gestion d'erreur lors que l'utilisateur tente d'accéder à une ressource qui n'existe pas et renvoi vers la page d'erreur 404 au lieu de tomber dans la page 500 de Baleen
- https://sentry.incubateur.net/organizations/betagouv/issues/164107/?project=221&query=is%3Aunresolved&referrer=issue-stream&stream_index=1

Corrige des erreurs Sentry

---

.github/workflows/integration-continue.yml
README.md
back/package-lock.json
back/package.json
front/_config.yml
front/lib-svelte/package.json
front/package.json
package-lock.json
package.json

Afin de standardiser notre approche de projet et de mutualiser les dépendances, nous utilisons désormais des workspaces. Le projet se matérialise actuellement avec trois workspaces : 
- back
- front (pour la partie statique avec Jekyll)
- front/lib-svelte (pour la partie front dynamique)

Ajoute des workspaces NPM

---

front/lib-svelte/package.json
package-lock.json

... suite à la montée de version Dependabot la dépendance "@types/axios" casse le typage Typescript dans le svelte.

[CORRECTION] Corrige les types Axios au niveau de lib-svelte

---

back/src/admin/consoleAdministration.ts
back/tests/api/ressourceFavori.spec.ts
back/tests/api/ressourceFavoris.spec.ts
back/tests/persistance/entrepotUtilisateurMemoire.ts

Dans un sous-répertoire des sources pour que celle-ci soit compilée dans dist-back et accessible dans l’environnement de production

Déplace la console d’administration

---

back/src/admin/consoleAdministration.ts
back/src/infra/entrepotUtilisateurMPAPostgres.ts

...en fonction de MPA et de Brevo. Normalement, MPA supporte 100 requêtes par minutes, donc 1 pour 600ms; on prend 700 pour avoir de la marge. Brevo supporte 10 RPS, donc 1 requête pour 100ms; on prend 150ms pour avoir de la marge.

Ajuste les rythmes de cadencement

---

back/src/infra/utilisateurBDD.ts
back/src/metier/utilisateur.ts

... L'id de la liste des favori était mis par défaut à `string vide` ce qui a causé une erreur lors de l'insertion en BDD Knex attends un champ au format UUID et cette valeur est interdite. Pour résoudre ce problème la valeur par défaut est mise à `undefined`.

[CORRECTION] Corrige l'inscription qui été bloqué lors de la soumission du formulaire

---

back/src/api/mon-aide-cyber/ressourceDemandesAide.ts
back/src/infra/adaptateurMonAideCyber.ts
back/tests/api/mon-aide-cyber/ressourceDemandesAide.spec.ts
front/lib-svelte/src/demande-aide-mon-aide-cyber/DemandeAideMAC.svelte
front/lib-svelte/src/demande-aide-mon-aide-cyber/DonneesFormulaireDemandeAide.ts
front/lib-svelte/src/demande-aide-mon-aide-cyber/FormulaireDemandeAide.svelte
front/lib-svelte/src/ui/Alerte.svelte

En vue de pouvoir gérer les demandes émanant depuis l’annuaire Aidant depuis MonAideCyber

[MonAideCyber] Prends en compte le nom d’usage ainsi que l’identifiant de l’utilisateur MAC

---

front/lib-svelte/src/demande-aide-mon-aide-cyber/FormulaireDemandeAide.svelte

Ajoute également des early return dans la gestion des paramètres fournis dans l’URL

[MonAideCyber] Modifie le nom du paramètre donné en URL ’utilisateur-mac’ devient ’email-utilisateur-mac’

---

back/package.json

Aujourd'hui c'est récurrent de se retrouver en PR avec des erreurs de types ou de compilation après un refactoring.
Ajouter ce script permet de vérifier la validité de la compilation à chaque fois que l'on lance les tests backend et fluidifiera et faciltera le processus de développement et de pull request.

Ajoute une vérification typescript lors des tests back

---

back/src/api/mon-aide-cyber/ressourceDemandesAide.ts
back/src/infra/adaptateurMonAideCyber.ts
back/tests/api/mon-aide-cyber/ressourceDemandesAide.spec.ts
front/lib-svelte/src/demande-aide-mon-aide-cyber/DemandeAideMAC.svelte
front/lib-svelte/src/demande-aide-mon-aide-cyber/DonneesFormulaireDemandeAide.ts

MonAideCyber a besoin du SIRET afin de récupérer des informations ultérieurement auprès de l’API recherche entreprise

[CYBERDEPART] Ajoute le SIRET lors de la demande d’Aide

---

front/lib-svelte/src/ui/formulaire/SelectionOrganisation.svelte

... En lien avec une remontée d'erreur dans Sentry : https://sentry.incubateur.net/organizations/betagouv/issues/170359/?project=221&referrer=webhooks_plugin. Il semblerait que dans certains cas l'annuaire d'organisation puisse renvoyer une réponse avec des data qui n'ont pas de suggestions défini. Peut être il faudrait mettre en place une gestion d'erreur plus fine dans ce cas afin de données des informations à l'utilisateur et ainsi qu'il puisse se débloquer.

[CORRECTION] Evite de tomber en erreur si suggestions n'est pas défini

---

back/src/admin/consoleAdministration.ts
back/src/bus/cablage.ts
back/src/bus/consigneEvenementProprieteTestRevendiqueeDansJournal.ts
back/src/infra/adaptateurJournal.ts
back/tests/bus/consigneEvenementProprieteTestRevendiqueeDansJournal.spec.ts
package.json

Actuellement, l’email est envoyé en clair dans l’événement `PROPRIETE_TEST_REVENDIQUEE`. Nous voulons désormais hacher cet email et corriger tous les événements déjà publiés.

Hache l’email dans l’événement du journal de revendication d’un test

---

front/_data/meta-description.yml
front/_includes/head.html

...afin de référencer ces pages dans les moteurs de recherche. La configuration se fait dans un fichier au format YML qui contient toutes les descriptions du site.

[SEO] Ajoute une balise meta `description` à chaque page

---

.env.template
back/migrations/20250612122433_ajouteColonneHacheEmailUtilisateurs.ts
back/migrations/20250612123742_remplisColonnesHacheEmailUtilisateur.ts
back/migrations/20250613070435_creationTableVersioningSecretHachage.ts
back/package.json
back/src/admin/consoleAdministration.ts
back/src/bus/cablage.ts
back/src/bus/consigneEvenementCompteCreeDansJournal.ts
back/src/bus/consigneEvenementMAJFavorisUtilisateurDansJournal.ts
back/src/bus/consigneEvenementProprieteTestRevendiqueeDansJournal.ts
back/src/infra/adaptateurEnvironnement.ts
back/src/infra/adaptateurHachage.ts
back/src/infra/entrepotUtilisateurMPAPostgres.ts
back/src/infra/utilisateurBDD.ts
back/src/serveur.ts
back/tests/api/fauxObjets.ts
back/tests/bus/consigneEvenementCompteCreeDansJournal.spec.ts
back/tests/bus/consigneEvenementMAJFavorisUtilisateurDansJournal.spec.ts
back/tests/bus/consigneEvenementProprieteTestRevendiqueeDansJournal.spec.ts
back/tests/infra/adaptateurEnvironnement.spec.ts
back/tests/infra/adaptateurHachage.spec.ts
package-lock.json

...afin de pouvoir ensuite chiffrer les données de l'utilisateur
> [!WARNING]
> Il faut ajouter la variable d'environnement `HACHAGE_SECRET_DE_HACHAGE_1` avant déploiement et sauvegarder précieusement cette valeur
> [!IMPORTANT]
> Il faut après déploiement exécuter la migration `consoleAdmin.sauvegardeLesEmpreintesDesSecretsDeHachage()` et `consoleAdmin.migreLesHashSha256DuJournal()`

Sauvegarde les hashs des emails utilisateur

---

back/src/infra/adaptateurEnvironnement.ts
back/src/infra/adaptateurHachage.ts
back/src/infra/entrepotSecretHachagePostgres.ts
back/src/infra/serviceVerificationCoherenceSecretsHachage.ts
back/src/serveur.ts
back/tests/api/fauxObjets.ts
back/tests/infra/adaptateurEnvironnement.spec.ts
back/tests/infra/serviceVerificationCoherenceSecretsHachage.spec.ts

On vérifie au démarrage les empreintes stockées dans la tables `secrets_hachage` en les comparant avec les variables de la configuration du serveur. 
En cas de discordance, le serveur s’arrête. 
:warning: If faut merger #346 avant celle-ci.

Verifie les secrets de hachage au démarrage

---

front/assets/styles/carte-item.scss
front/lib-svelte/src/catalogue/ContenuCarteItem.svelte

afin de permettre à la zone de tags de prendre de la place dans la zone de titre
Avant : 
Après :

[CORRECTION] Utilise un contenu plus flexible sur le catalogue

---

front/lib-svelte/test/catalogue/stores/catalogue.store.spec.ts
front/lib-svelte/test/catalogue/stores/catalogueFiltre.store.spec.ts
front/lib-svelte/test/catalogue/stores/nombreResultats.store.spec.ts
front/lib-svelte/test/catalogue/stores/rechercheParDroitAcces.store.spec.ts
front/lib-svelte/test/stores/profil.store.spec.ts

Quelques erreurs sont restées dans les tests depuis que nous avons activé eslint

[SOIN] Corrige des erreurs eslint dans les tests

---

back/src/api/ressourceRetoursExperience.ts
back/src/bus/cablage.ts
back/src/bus/consigneEvenementRetourExperienceDonneDansJournal.ts
back/src/bus/evenements/retourExperienceDonne.ts
back/src/infra/adaptateurJournal.ts
back/tests/api/ressourceRetoursExperience.spec.ts
back/tests/bus/consigneEvenementRetourExperienceDonneDansJournal.spec.ts

Publie un événement et le consigne dans le journal. L’événement est `RETOUR_EXPERIENCE_DONNE` et il contient la raison et le mail de contact (éventuel) haché.

Consigne les retours d’expérience dans le journal

---

front/lib-svelte/src/demande-aide-mon-aide-cyber/DemandeAideMAC.svelte

...pour ne pas voir cette modale si l’utilisateur a correctement soumis le formulaire

[DIAG] N’affiche pas la modale de sortie en cas de succès

---

front/_ressources/cyber-enjeux-pro.md
front/_ressources/cyber-enjeux.md
front/_ressources/risques-cyber.md

... plutôt que celui de MSS. 
En effet, les ressources ont été déplacées dans un cellar dédié à MSC, cela évite d’utiliser les cellar MAC et MSS pour y stocker des ressources spécifiques à MSC. 
Cependant, les ressources spécifiques à MSS et à MAC sont toujours téléchargées depuis leurs cellars respectifs.

Utilise les ressources volumineuses depuis le cellar MSC

---

front/lib-svelte/src/test-maturite/HistoriqueTests.svelte
front/lib-svelte/src/test-maturite/MaturiteUtilisateur.svelte
front/lib-svelte/src/test-maturite/OngletsTest.svelte
front/lib-svelte/src/test-maturite/PropositionRefaireTest.svelte
front/lib-svelte/src/test-maturite/ResultatsMonOrganisation.svelte
front/lib-svelte/src/test-maturite/ResultatsTestMaturite.svelte
front/lib-svelte/src/test-maturite/TuilesMaturite.svelte
front/lib-svelte/src/ui/ConteneurOnglets.svelte
front/lib-svelte/src/ui/Onglet.svelte

- Change le wording du bandeau
- Supprime l'auto-scroll lors du clic sur l'onglet  "maturité cyber de votre organisation"
- Clic sur l'onglet historique depuis le détail d'un test ramène sur l'historique
- Conserver la bordure de l’onglet dans une résolution inférieure à 458px
- Corrige le style du lien "Refaire le test"

Applique les retours graphiques sur onglet historique

---

front/lib-svelte/src/test-maturite/BoutonsPartageTest.svelte

Quand on est dans la partie connectée du test de maturité (n’importe quel), le partage du lien doit se faire vers le test public

[CORRECTION] Partage le lien vers le test public

---

front/lib-svelte/src/test-maturite/EncartDeRecommandationSelonMaturite.svelte
front/lib-svelte/src/test-maturite/TuilesMaturite.svelte

On affiche désormais l'encart "demande de diagnostics" sur un résultat `intermédiaire`, comme on le ferait avec un résultat `insuffisant` ou `émergent`

[PAGE RESULTAT TEST DE MATURITE] Resultat intermediaire diag cyber

---

front/scripts/sentry.js

...car nous n’avons pas axios dans nos dépendances du front, uniquement dans le contexte de svelte, où il est intégré au paquet grâce à vite. Plutôt que de rajouter une dépendance peu utile et contraignante vers axios, nous préférons donc ne pas vérifier qu’il s’agit d’une erreur axios (après tout, si c’était une erreur fetch nous voudrions également l’ignorer) et nous baser uniquement sur le code de l’exception d’origine qui est suffisamment explicite (`ECONNABORTED`) pour nous permettre d’ignorer l’erreur.

[BUG] Corrige le problème `Axios is not defined`

---

back/src/infra/markdown.ts
back/src/infra/messagerieMattermost.ts
back/tests/infra/markdown.spec.ts

Le contenu de la modale de retour expérience est envoyé sur mattermost qui interprète le message au format markdown. Le champ précision est libre et il est donc possible d’envoyer des messages contenant du formatage et des images non désirables sur mattermost. Nous aseptisons donc ce champ pour éviter tout souci.

[MODALE SORTIE] Aseptise les retours expériences

---

front/lib-svelte/src/identification/ZoneIdentification.svelte
front/lib-svelte/src/navigation/NavigationBureau.svelte
front/lib-svelte/src/navigation/NavigationMobile.svelte
front/lib-svelte/src/test-maturite/ResultatsTestMaturite.svelte
front/lib-svelte/src/test-maturite/TestMaturite.svelte
front/resultats-session-groupe.html
front/session-groupe.html

La liste des changements : 
- MODE_DECO : renommer le menu "Tester votre maturité cyber" en "Test de maturité cyber", et le déplacer à droite du menu "Accueil"
- Fusioner les menus "Catalogue des services" et "Nos sélections" dans un menu "Catalogue et sélections"
- Modifier le menu "Contacts utiles" en sous menu, et lui rajouter l'entrée "Prestataires"
- Rajouter un menu "Financements" en 5eme position
- MODE_CONNECTE : déplacer le menu "Maturité cyber" au début
- MODE_CONNECTE : déplacer le menu "Favoris" en 3eme position
- MODE_CONNECTE : Ajouter l'entrée "Contacts de votre région" au sous menu "Contacts utiles"
- MODE_CONNECTE : afficher le bouton "Diagnostic cyber gratuit" (actuellement en mode déco seul) à la place du menu "Diagnostic cyber"
- MODE_CONNECTE : le nom de l'utilisateur …

[NAVIGATION] Modifie la barre de navigation

---

front/_services/secnum-academie.md

Cette pauvre petite fiche pour SecNumAcadémie n'avait pas de lien - c'est désormais le cas

ajout du lien vers secnumacademie

---

front/assets/styles/test-maturite.scss

...dans l'encart promotionnel de l'espace connecté. Pour cela on ne centre les cartes qu'à partir de 576px de large, sinon le centrage implique un découpage de la carte de gauche vers laquelle il n'est pas possible de scroller
Avant :
Après :

Évite de couper les cartes

---

front/lib-svelte/src/test-maturite/TestMaturite.svelte

...qui est normale puisque lorsque l’utilisateur est connecté, on cherche à savoir s’il a déjà un test de maturité. L’API renvoie une « erreur » qui est attendue et normale mais qui n’apparaissait pas dans le catch.

Supprime une alerte 404
